import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Container, Box, Stack, Title, Group } from "@mantine/core";
import { Branding } from "../src/components/index";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={(theme) => ({
          backgroundColor: theme.colors.primary[0],
          height: "100vh",
          paddingTop: theme.spacing.md,
        })}
      >
        <Container fluid>
          <Stack>
            <Branding />
          </Stack>
        </Container>
      </Box>
    </>
  );
};

export default Home;
