import type { NextPage } from "next";
import Head from "next/head";

import {
  Container,
  Box,
  Stack,
  Title,
  Group,
  TextInput,
  Button,
  PasswordInput,
  Image,
  useMantineTheme,
} from "@mantine/core";
import { Branding } from "../src/components/index";
import { useForm } from "react-hook-form";

const Home: NextPage = () => {
  const { register, handleSubmit } = useForm();
  const onSubmit = (data) => console.log(data);
  const theme = useMantineTheme();
  return (
    <>
      <Head>
        <title>Forms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={(theme) => ({
          backgroundColor: theme.colors.primary[0],
          height: "100vh",
        })}
      >
        Forms
      </Box>
    </>
  );
};

export default Home;
