import type { NextPage } from "next";
import Head from "next/head";

import {
  Container,
  Box,
  Stack,
  Title,
  Group,
  TextInput,
  Button,
  PasswordInput,
  Image,
  useMantineTheme,
} from "@mantine/core";
import { Branding } from "../src/components/index";
import { useForm } from "react-hook-form";

const Login: NextPage = () => {
  const { register, handleSubmit } = useForm();
  const onSubmit = (data) => console.log(data);
  const theme = useMantineTheme();
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={(theme) => ({
          backgroundColor: theme.colors.primary[0],
          height: "100vh",
        })}
      >
        <Group
          sx={(theme) => ({
            width: "100%",
            height: "100%",
            flexWrap: "nowrap",
          })}
        >
          <Container
            fluid={true}
            px="xl"
            py="xl"
            sx={(theme) => ({
              width: "50%",
              height: "100%",
              [`@media (max-width: ${theme.breakpoints.lg}px)`]: {
                width: "75%",
              },
              [`@media (max-width: ${theme.breakpoints.sm}px)`]: {
                width: "85%",
              },
              [`@media (max-width: ${theme.breakpoints.xs}px)`]: {
                width: "100%",
              },
            })}
          >
            <Stack
              sx={(theme) => ({
                height: "100%",
              })}
              justify="space-between"
            >
              <Branding />
              <Stack
                sx={(theme) => ({
                  width: "100%",
                  gap: theme.spacing.xl,
                })}
              >
                <Title
                  order={4}
                  sx={(theme) => ({
                    color: theme.colors.quaternary[0],
                    fontSize: theme.fontSizes.xl,
                  })}
                >
                  Login
                </Title>
                <form onSubmit={handleSubmit(onSubmit)}>
                  <Stack
                    sx={(theme) => ({
                      gap: theme.spacing.xl,
                    })}
                  >
                    <TextInput
                      sx={(theme) => ({
                        label: {
                          color: theme.colors.gray[6],
                        },
                        input: {
                          borderColor: theme.colors.secondary[0],
                          borderWidth: 2,
                          borderStyle: "solid",
                          "&:hover": {
                            borderColor: theme.colors.gray[5],
                          },
                          "&:focus": {
                            borderColor: theme.colors.tertiary[0],
                          },
                        },
                      })}
                      placeholder="Your Email"
                      label="E-Mail"
                      required
                      size="md"
                      {...register("email")}
                    />
                    <PasswordInput
                      styles={{
                        defaultVariant: {
                          borderColor: theme.colors.secondary[0],
                          borderWidth: 2,
                          borderStyle: "solid",
                          "&:focus-within": {
                            borderColor: theme.colors.tertiary[0],
                          },
                          "&:not(&:focus-within)&:hover": {
                            borderColor: theme.colors.gray[5],
                          },
                        },
                      }}
                      sx={(theme) => ({
                        label: {
                          color: theme.colors.gray[6],
                        },
                      })}
                      size="md"
                      placeholder="Password"
                      label="Password"
                      required
                      {...register("password")}
                    />
                    <Group>
                      <Button
                        size="md"
                        sx={(theme) => ({
                          backgroundColor: theme.colors.tertiary[0],
                          "&:hover": {
                            backgroundColor: theme.fn.darken(
                              theme.colors.tertiary[0],
                              0.1
                            ),
                          },
                          alignSelf: "start",
                        })}
                      >
                        Login
                      </Button>
                      <Button
                        variant="subtle"
                        size="md"
                        sx={(theme) => ({
                          color: theme.colors.gray[6],
                          "&:hover": {
                            backgroundColor: theme.colors.gray[2],
                          },
                        })}
                      >
                        Forgot Password
                      </Button>
                    </Group>
                  </Stack>
                </form>
              </Stack>
              <Box></Box>
            </Stack>
          </Container>

          <Box
            sx={(theme) => ({
              width: "50%",
              height: "100%",
              backgroundColor: theme.colors.tertiary[0],
              [`@media (max-width: ${theme.breakpoints.lg}px)`]: {
                width: "25%",
              },
              [`@media (max-width: ${theme.breakpoints.sm}px)`]: {
                width: "15%",
              },
              [`@media (max-width: ${theme.breakpoints.xs}px)`]: {
                width: 0,
              },
            })}
          ></Box>
        </Group>
      </Box>
    </>
  );
};

export default Login;
